# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Azat Murtazin
author: Azat Murtazin
email: murtazin.azat@gmail.com

# site:
#   author: Azat Murtazin
#   email: murtazin.azat@gmail.com

# description: >
#   Blog, just blog.

baseurl: ""
url: "https://azatmurtazin.github.io"

github_username: azatmurtazin
facebook_username: murtazin84
instagram_username: burzumko13
linkedin_username: azatmurtazin

disqus:
  shortname: azat-murtazin-at-github-io

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# minima:
#   social_links:
#     github: azatmurtazin
#     facebook: murtazin84
#     instagram: burzumko13
#     linkedin: azatmurtazin
#     telegram: AzatMurtazin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
